In [1]:
#Importing libraries
import csv
import os
import pandas as pd
import numpy as np

In [2]:
#path to GNP csv file
population = os.path.join('input/wb_population_total.csv')

#opening and converting the csv to a dataframe
population_df = pd.read_csv(population, skiprows=[1,2,3], header=1)

population_df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54208.0,55434.0,56234.0,56699.0,57029.0,57357.0,...,102565.0,103165.0,103776.0,104339.0,104865.0,105361.0,105846.0,106310.0,106766.0,NaN
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130836765.0,134159786.0,137614644.0,141202036.0,144920186.0,148769974.0,...,547482863.0,562601578.0,578075373.0,593871847.0,609978946.0,626392880.0,643090131.0,660046272.0,677243299.0,NaN
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8996967.0,9169406.0,9351442.0,9543200.0,9744772.0,9956318.0,...,31161378.0,32269592.0,33370804.0,34413603.0,35383028.0,36296111.0,37171922.0,38041757.0,38928341.0,NaN
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,96396419.0,98407221.0,100506960.0,102691339.0,104953470.0,107289875.0,...,370243017.0,380437896.0,390882979.0,401586651.0,412551299.0,423769930.0,435229381.0,446911598.0,458803476.0,NaN
4,Angola,AGO,"Population, total",SP.POP.TOTL,5454938.0,5531451.0,5608499.0,5679409.0,5734995.0,5770573.0,...,25107925.0,26015786.0,26941773.0,27884380.0,28842482.0,29816769.0,30809787.0,31825299.0,32866268.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Population, total",SP.POP.TOTL,947000.0,966000.0,994000.0,1022000.0,1050000.0,1078000.0,...,1807106.0,1818117.0,1812771.0,1788196.0,1777557.0,1791003.0,1797085.0,1788878.0,1775378.0,NaN
262,"Yemen, Rep.",YEM,"Population, total",SP.POP.TOTL,5315351.0,5393034.0,5473671.0,5556767.0,5641598.0,5727745.0,...,24473176.0,25147112.0,25823488.0,26497881.0,27168210.0,27834811.0,28498683.0,29161922.0,29825968.0,NaN
263,South Africa,ZAF,"Population, total",SP.POP.TOTL,17099836.0,17524533.0,17965733.0,18423157.0,18896303.0,19384838.0,...,52832659.0,53687125.0,54544184.0,55386369.0,56207649.0,57009751.0,57792520.0,58558267.0,59308690.0,NaN
264,Zambia,ZMB,"Population, total",SP.POP.TOTL,3070780.0,3164330.0,3260645.0,3360099.0,3463211.0,3570466.0,...,14465148.0,14926551.0,15399793.0,15879370.0,16363449.0,16853608.0,17351714.0,17861034.0,18383956.0,NaN
265,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,3776679.0,3905038.0,4039209.0,4178726.0,4322854.0,4471178.0,...,13115149.0,13350378.0,13586710.0,13814642.0,14030338.0,14236599.0,14438812.0,14645473.0,14862927.0,NaN

In [9]:
#rename columns
population = population_df.rename(columns={"Country Name": "country", "Country Code":"country_code"})

In [10]:
# Dropping unecessary columns
population_clean = population[["country", "country_code", "1990","1991","1992","1993","1994"
                        ,"1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007"
                        ,"2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020"]]

In [11]:
countries_list = pd.unique(population_clean['country'])
len(countries_list)

266

In [22]:
df_transpose = population_clean.transpose().iloc[:,0:1]

In [27]:
df_transpose.values[2:]

array([[62152.0],
       [64623.0],
       [68240.0],
       [72495.0],
       [76705.0],
       [80324.0],
       [83211.0],
       [85450.0],
       [87280.0],
       [89009.0],
       [90866.0],
       [92892.0],
       [94992.0],
       [97016.0],
       [98744.0],
       [100028.0],
       [100830.0],
       [101226.0],
       [101362.0],
       [101452.0],
       [101665.0],
       [102050.0],
       [102565.0],
       [103165.0],
       [103776.0],
       [104339.0],
       [104865.0],
       [105361.0],
       [105846.0],
       [106310.0],
       [106766.0]], dtype=object)

In [19]:
population_clean

,country,country_code,1990,1991,1992,1993,1994,1995,1996,1997,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Aruba,ABW,62152.0,64623.0,68240.0,72495.0,76705.0,80324.0,83211.0,85450.0,...,102050.0,102565.0,103165.0,103776.0,104339.0,104865.0,105361.0,105846.0,106310.0,106766.0
1,Africa Eastern and Southern,AFE,304648010.0,313394693.0,322270073.0,331265579.0,340379934.0,349605660.0,358953595.0,368440591.0,...,532760424.0,547482863.0,562601578.0,578075373.0,593871847.0,609978946.0,626392880.0,643090131.0,660046272.0,677243299.0
2,Afghanistan,AFG,12412311.0,13299016.0,14485543.0,15816601.0,17075728.0,18110662.0,18853444.0,19357126.0,...,30117411.0,31161378.0,32269592.0,33370804.0,34413603.0,35383028.0,36296111.0,37171922.0,38041757.0,38928341.0
3,Africa Western and Central,AFW,204803865.0,210332267.0,215976366.0,221754806.0,227692136.0,233807627.0,240114179.0,246613750.0,...,360285439.0,370243017.0,380437896.0,390882979.0,401586651.0,412551299.0,423769930.0,435229381.0,446911598.0,458803476.0
4,Angola,AGO,11848385.0,12248901.0,12657361.0,13075044.0,13503753.0,13945205.0,14400722.0,14871572.0,...,24220660.0,25107925.0,26015786.0,26941773.0,27884380.0,28842482.0,29816769.0,30809787.0,31825299.0,32866268.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,1862000.0,1898000.0,1932000.0,1965000.0,1997000.0,2029000.0,2059000.0,2086000.0,...,1791000.0,1807106.0,1818117.0,1812771.0,1788196.0,1777557.0,1791003.0,1797085.0,1788878.0,1775378.0
262,"Yemen, Rep.",YEM,11709987.0,12302127.0,12954157.0,13634082.0,14297617.0,14913313.0,15469274.0,15975676.0,...,23807586.0,24473176.0,25147112.0,25823488.0,26497881.0,27168210.0,27834811.0,28498683.0,29161922.0,29825968.0
263,South Africa,ZAF,36800507.0,37718952.0,38672611.0,39633754.0,40564061.0,41435761.0,42241007.0,42987456.0,...,52003759.0,52832659.0,53687125.0,54544184.0,55386369.0,56207649.0,57009751.0,57792520.0,58558267.0,59308690.0
264,Zambia,ZMB,8036849.0,8246662.0,8451346.0,8656484.0,8869745.0,9096608.0,9339740.0,9597610.0,...,14023199.0,14465148.0,14926551.0,15399793.0,15879370.0,16363449.0,16853608.0,17351714.0,17861034.0,18383956.0
265,Zimbabwe,ZWE,10432409.0,10681008.0,10900511.0,11092775.0,11261752.0,11410721.0,11541215.0,11653254.0,...,12894323.0,13115149.0,13350378.0,13586710.0,13814642.0,14030338.0,14236599.0,14438812.0,14645473.0,14862927.0

In [ ]:
for country in countries_list:
    df.loc['country']

In [18]:
population_clean.loc[:,'Aruba']

KeyError: 'Aruba'